import * as colors from "./colors";
import * as theme from "../settings/environment";
import { PropsColorsCore } from "./Models/type.colors";
import { PropsTextCore } from "./Models/type.text";
import FONT_WEIGHT from "./fonts";

export const lightColors: PropsColorsCore = {
  ...colors,
};

const fontSize = {
  smaller: theme.FONT_SIZE_SMALLER,
  small: theme.FONT_SIZE_SMALL,
  middle: theme.FONT_SIZE_MIDDLE,
  standard: theme.FONT_SIZE_STANDARD,
  large: theme.FONT_SIZE_LARGE,
  larger: theme.FONT_SIZE_LARGER,
  big: theme.FONT_SIZE_BIG,
  bigger: theme.FONT_SIZE_BIGGER,
  xl: theme.FONT_SIZE_XL,
  display1: theme.FONT_SIZE_DISPLAY_1,
  display2: theme.FONT_SIZE_DISPLAY_2,
  display3: theme.FONT_SIZE_DISPLAY_3,
};

const fontWeight = {
  light: theme.FONT_WEIGHT_LIGHT,
  regular: theme.FONT_WEIGHT_REGULAR,
  medium: theme.FONT_WEIGHT_MEDIUM,
  bold: theme.FONT_WEIGHT_BOLD,
};

const borderRadius = {
  none: theme.BORDER_RADIUS_NONE,
  smaller: theme.BORDER_RADIUS_SMALLER,
  small: theme.BORDER_RADIUS_SMALL,
  medium: theme.BORDER_RADIUS_MEDIUM,
  large: theme.BORDER_RADIUS_LARGE,
  big: theme.BORDER_RADIUS_BIG,
  larger: theme.BORDER_RADIUS_LARGER,
  pill: theme.BORDER_RADIUS_PILL,
  circle: theme.BORDER_RADIUS_CIRCLE,
};

const borderWidth = {
  none: theme.BORDER_WIDTH_NONE,
  smaller: theme.BORDER_WIDTH_SMALLER,
  small: theme.BORDER_WIDTH_SMALL,
  medium: theme.BORDER_WIDTH_MEDIUM,
  half: theme.BORDER_WIDTH_HALF,
  large: theme.BORDER_WIDTH_LARGE,
  xxl: theme.BORDER_WIDTH_XXL,
};

const opacityLevel = {
  small: theme.OPACITY_LEVEL_SMALL,
  none: theme.OPACITY_LEVEL_NONE,
};

const shadow = {
  level0: theme.SHADOW_LEVEL0,
  level1: theme.SHADOW_LEVEL1,
  level2: theme.SHADOW_LEVEL2,
  level3: theme.SHADOW_LEVEL3,
  level4: theme.SHADOW_LEVEL4,
  level5: theme.SHADOW_LEVEL5,
};

const lineHeight = {
  tight: theme.LINE_HEIGHT_TIGHT,
  fair: theme.LINE_HEIGHT_FAIR,
  distant: theme.LINE_HEIGHT_DISTANT,
};

const letterSpacing = {
  xs: -0.2,
  xxs: -0.4,
};

const spaces = {
  margins: {
    flat: {
      quark: theme.MARGIN_FLAT_QUARK,
      nano: theme.MARGIN_FLAT_NANO,
      xxxxs: theme.MARGIN_FLAT_XXXXS,
      xxxs: theme.MARGIN_FLAT_XXXS,
      xxs: theme.MARGIN_FLAT_XXS,
      xs: theme.MARGIN_FLAT_XS,
      tiny: theme.MARGIN_FLAT_TINY,
      smaller: theme.MARGIN_FLAT_SMALLER,
      small: theme.MARGIN_FLAT_SMALL,
      middle: theme.MARGIN_FLAT_MIDDLE,
      meddium: theme.MARGIN_FLAT_MEDIUM,
      large: theme.MARGIN_FLAT_LARGE,
      larger: theme.MARGIN_FLAT_LARGER,
      xl: theme.MARGIN_FLAT_XL,
      xxl: theme.MARGIN_FLAT_XXL,
      xxxl: theme.MARGIN_FLAT_XXXL,
      huge: theme.MARGIN_FLAT_HUGE,
    },
    standing: {
      quark: theme.MARGIN_STANDING_QUARK,
      nano: theme.MARGIN_STANDING_NANO,
      xs: theme.MARGIN_STANDING_XS,
      smaller: theme.MARGIN_STANDING_SMALLER,
      half: theme.MARGIN_STANDING_HALF,
      small: theme.MARGIN_STANDING_SMALL,
      middle: theme.MARGIN_STANDING_MIDDLE,
      medium: theme.MARGIN_STANDING_MEDIUM,
      large: theme.MARGIN_STANDING_LARGE,
      larger: theme.MARGIN_STANDING_LARGER,
    },
  },
  padding: {
    inner: {
      small: theme.PADDING_INNER_SMALL,
      middle: theme.PADDING_INNER_MIDDLE,
      medium: theme.PADDING_INNER_MEDIUM,
      large: theme.PADDING_INNER_LARGE,
      great: theme.PADDING_INNER_GREAT,
      larger: theme.PADDING_INNER_LARGER,
      xl: theme.PADDING_INNER_XL,
      xxxl: theme.PADDING_INNER_XXXL,
    },
    squish: {
      xxxss: `${theme.PADDING_SQUISH_XXXSS[0]}px ${theme.PADDING_SQUISH_XXXS[1]}px`,
      xxxs: `${theme.PADDING_SQUISH_XXXS[0]}px ${theme.PADDING_SQUISH_XXXS[1]}px`,
      xxs: `${theme.PADDING_SQUISH_XXS[0]}px ${theme.PADDING_SQUISH_XXS[1]}px`,
      xs: `${theme.PADDING_SQUISH_XS[0]}px ${theme.PADDING_SQUISH_XS[1]}px`,
      quarck: `${theme.PADDING_SQUISH_QUARCK[0]}px ${theme.PADDING_SQUISH_QUARCK[1]}px`,
      smaller: `${theme.PADDING_SQUISH_SMALLER[0]}px ${theme.PADDING_SQUISH_SMALLER[1]}px`,
      small: `${theme.PADDING_SQUISH_SMALL[0]}px ${theme.PADDING_SQUISH_SMALL[1]}px`,
      short: `${theme.PADDING_SQUISH_SHORT[0]}px ${theme.PADDING_SQUISH_SHORT[1]}px`,
      middle: `${theme.PADDING_SQUISH_MIDDLE[0]}px ${theme.PADDING_SQUISH_MIDDLE[1]}px`,
      minor: `${theme.PADDING_SQUISH_MINOR[0]}px ${theme.PADDING_SQUISH_MINOR[1]}px`,
      medium: `${theme.PADDING_SQUISH_MEDIUM[0]}px ${theme.PADDING_SQUISH_MEDIUM[1]}px`,
      large: `${theme.PADDING_SQUISH_LARGE[0]}px ${theme.PADDING_SQUISH_LARGE[1]}px`,
    },
    stretch: {
      small: `${theme.PADDING_STRETCH_SMALL[0]}px ${theme.PADDING_STRETCH_SMALL[1]}px`,
      middle: `${theme.PADDING_STRETCH_MIDDLE[0]}px ${theme.PADDING_STRETCH_MIDDLE[1]}px`,
      half: `${theme.PADDING_STRETCH_HALF[0]}px ${theme.PADDING_STRETCH_HALF[1]}px`,
      medium: `${theme.PADDING_STRETCH_MEDIUM[0]}px ${theme.PADDING_STRETCH_MEDIUM[1]}px`,
      large: `${theme.PADDING_STRETCH_LARGE[0]}px ${theme.PADDING_STRETCH_LARGE[1]}px`,
      larger: `${theme.PADDING_STRETCH_LARGER[0]}px ${theme.PADDING_STRETCH_LARGER[1]}px`,
    },
  },
};

const styleText: PropsTextCore = {
  heading: {
    xxxlr: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.display2,
      fontWeight: fontWeight.regular,
      lineHeight: lineHeight.tight,
    },
    xxxlm: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.display2,
      fontWeight: fontWeight.medium,
      lineHeight: lineHeight.tight,
    },
    xxxl: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.display2,
      fontWeight: fontWeight.bold,
      lineHeight: lineHeight.tight,
    },
    xxl: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.display1,
      fontWeight: fontWeight.bold,
      lineHeight: lineHeight.fair,
    },
    md: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.xl,
      fontWeight: fontWeight.medium,
      lineHeight: lineHeight.fair,
    },
    mdl: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.xl,
      fontWeight: fontWeight.regular,
      lineHeight: lineHeight.fair,
    },
  },
  subtitle: {
    xxlb: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.big,
      fontWeight: fontWeight.bold,
      letterSpacing: letterSpacing.xs,
      lineHeight: lineHeight.tight,
    },
    xxxxl: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.bigger,
      fontWeight: fontWeight.medium,
      letterSpacing: letterSpacing.xs,
      lineHeight: lineHeight.tight,
    },
    xxxl: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.bigger,
      fontWeight: fontWeight.regular,
      letterSpacing: letterSpacing.xs,
      lineHeight: lineHeight.tight,
    },
    xxl: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.big,
      fontWeight: fontWeight.medium,
      letterSpacing: letterSpacing.xs,
      lineHeight: lineHeight.tight,
    },
    xl: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.big,
      fontWeight: fontWeight.regular,
      letterSpacing: letterSpacing.xs,
      lineHeight: lineHeight.tight,
    },
    x: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.big,
      fontWeight: fontWeight.light,
      letterSpacing: letterSpacing.xs,
      lineHeight: lineHeight.tight,
    },
    lg: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.larger,
      fontWeight: fontWeight.medium,
      letterSpacing: letterSpacing.xs,
      lineHeight: lineHeight.tight,
    },
    mdm: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.larger,
      fontWeight: fontWeight.regular,
      letterSpacing: letterSpacing.xs,
      lineHeight: lineHeight.tight,
    },
    md: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.larger,
      fontWeight: fontWeight.light,
      letterSpacing: letterSpacing.xs,
      lineHeight: lineHeight.tight,
    },
  },
  paragraph: {
    xxxxl: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.large,
      fontWeight: fontWeight.bold,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.tight,
    },
    xxxl: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.large,
      fontWeight: fontWeight.medium,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.tight,
    },
    xxl: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.large,
      fontWeight: fontWeight.regular,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.tight,
    },
    xxll: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.large,
      fontWeight: fontWeight.light,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.tight,
    },
    xl: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.standard,
      fontWeight: fontWeight.medium,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.fair,
    },
    lg: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.standard,
      fontWeight: fontWeight.regular,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.fair,
    },
    l: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.standard,
      fontWeight: fontWeight.light,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.fair,
    },
    mdm: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.middle,
      fontWeight: fontWeight.medium,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.fair,
    },
    md: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.middle,
      fontWeight: fontWeight.regular,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.fair,
    },
    mdl: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.middle,
      fontWeight: fontWeight.light,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.fair,
    },
    sml: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.small,
      fontWeight: fontWeight.medium,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.distant,
    },
    sm: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.small,
      fontWeight: fontWeight.regular,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.distant,
    },
    xs: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.small,
      fontWeight: fontWeight.light,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.distant,
    },
    xxs: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.smaller,
      fontWeight: fontWeight.bold,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.distant,
    },
    xxxs: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.smaller,
      fontWeight: fontWeight.regular,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.distant,
    },
    xxxxs: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.smaller,
      fontWeight: fontWeight.light,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.distant,
    },
  },
  link: {
    xl: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.standard,
      fontWeight: fontWeight.medium,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.distant,
    },
    lg: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.standard,
      fontWeight: fontWeight.regular,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.distant,
    },
    xs: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.small,
      fontWeight: fontWeight.regular,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.distant,
      textDecoration: "underline",
    },
    sm: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.small,
      fontWeight: fontWeight.regular,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.distant,
      textDecoration: "underline",
    },
    mdm: {
      font: FONT_WEIGHT.Barlow_400,
      fontSize: fontSize.middle,
      fontWeight: fontWeight.medium,
      letterSpacing: letterSpacing.xxs,
      lineHeight: lineHeight.tight,
      textDecoration: "underline",
    },
  },
};

const styleButton = {
  buttonPrimaryLarge: {
    width: theme.BUTTON_PRIMARY_LARGE_WIDTH,
    height: theme.BUTTON_PRIMARY_LARGE_HEIGHT,
    spacing: spaces.padding.stretch.middle,
    color: "PRYMARY_BASE_02",
    colorDisabled: "LIGHT_BASE_03",
    borderRadius: borderRadius.circle,
    text: {
      type: "paragraphXL",
      textColor: "LIGHT_BASE_01",
      textColorDisabled: "DARK_BASE_02",
    },
  },
  buttonPrimaryMedium: {
    width: theme.BUTTON_PRIMARY_MEDIUM_WIDTH,
    height: theme.BUTTON_PRIMARY_MEDIUM_HEIGHT,
    spacing: spaces.padding.stretch.small,
    color: "PRYMARY_BASE_02",
    colorDisabled: "LIGHT_BASE_03",
    borderRadius: borderRadius.circle,
    text: {
      type: "paragraphXL",
      textColor: "LIGHT_BASE_01",
      textColorDisabled: "DARK_BASE_02",
    },
  },
  buttonPrimarySmall: {
    width: theme.BUTTON_PRIMARY_SMALL_WIDTH,
    height: theme.BUTTON_PRIMARY_SMALL_HEIGHT,
    spacing: spaces.padding.stretch.small,
    color: "PRYMARY_BASE_02",
    colorDisabled: "LIGHT_BASE_03",
    borderRadius: borderRadius.circle,
    text: {
      type: "paragraphXL",
      textColor: "LIGHT_BASE_01",
      textColorDisabled: "DARK_BASE_02",
    },
  },
  buttonSecundaryLarge: {
    width: theme.BUTTON_SECUNDARY_LARGE_WIDTH,
    height: theme.BUTTON_SECUNDARY_LARGE_HEIGHT,
    spacing: spaces.padding.stretch.middle,
    color: "transparent",
    colorDisabled: "transparent",
    borderColor: "PRYMARY_BASE_02",
    borderColorDisabled: "LIGHT_BASE_05",
    borderWidth: borderWidth.small,
    borderRadius: borderRadius.circle,
    text: {
      type: "paragraphXL",
      textColor: "PRYMARY_BASE_02",
      textColorDisabled: "DARK_BASE_01",
    },
  },
  buttonSecundaryMedium: {
    width: theme.BUTTON_SECUNDARY_MEDIUM_WIDTH,
    height: theme.BUTTON_SECUNDARY_MEDIUM_HEIGHT,
    spacing: spaces.padding.stretch.middle,
    color: "transparent",
    colorDisabled: "transparent",
    borderColor: "PRYMARY_BASE_02",
    borderColorDisabled: "LIGHT_BASE_05",
    borderWidth: borderWidth.small,
    borderRadius: borderRadius.circle,
    text: {
      type: "paragraphXL",
      textColor: "PRYMARY_BASE_02",
      textColorDisabled: "DARK_BASE_01",
    },
  },
  buttonSecundarySmall: {
    width: theme.BUTTON_SECUNDARY_SMALL_WIDTH,
    height: theme.BUTTON_SECUNDARY_SMALL_HEIGHT,
    spacing: spaces.padding.stretch.middle,
    color: "transparent",
    colorDisabled: "transparent",
    borderColor: "PRYMARY_BASE_02",
    borderColorDisabled: "LIGHT_BASE_05",
    borderWidth: borderWidth.small,
    borderRadius: borderRadius.circle,
    text: {
      type: "paragraphXL",
      textColor: "PRYMARY_BASE_02",
      textColorDisabled: "DARK_BASE_01",
    },
  },
  primaryLargeCherry: {
    width: theme.BUTTON_PRIMARY_LARGE_WIDTH,
    height: theme.BUTTON_PRIMARY_LARGE_HEIGHT,
    spacing: spaces.padding.stretch.small,
    color: "PRYMARY_BASE_01",
    colorDisabled: "PRYMARY_BASE_01",
    borderRadius: borderRadius.pill,
    text: {
      type: "linkXL",
      textColor: "LIGHT_BASE_01",
      textColorDisabled: "LIGHT_BASE_01",
    },
  },
  secundaryLargeCherry: {
    width: theme.BUTTON_SECUNDARY_LARGE_WIDTH,
    height: theme.BUTTON_SECUNDARY_LARGE_HEIGHT,
    spacing: spaces.padding.stretch.small,
    color: "transparent",
    colorDisabled: "transparent",
    borderColor: "PRYMARY_BASE_02",
    borderColorDisabled: "PRYMARY_BASE_02",
    borderWidth: borderWidth.small,
    borderRadius: borderRadius.pill,
    text: {
      type: "linkXL",
      textColor: "PRYMARY_BASE_02",
      textColorDisabled: "PRYMARY_BASE_02",
    },
  },
  secundaryQuarck: {
    width: theme.BUTTON_SECUNDARY_QUARCK_WIDTH,
    height: theme.BUTTON_SECUNDARY_QUARCK_HEIGHT,
    spacing: spaces.padding.squish.xxxs,
    color: "transparent",
    colorDisabled: "transparent",
    borderColor: "PRYMARY_BASE_02",
    borderColorDisabled: "PRYMARY_BASE_02",
    borderWidth: borderWidth.smaller,
    borderRadius: borderRadius.pill,
    text: {
      type: "paragraphMDM",
      textColor: "PRYMARY_BASE_02",
      textColorDisabled: "DARK_BASE_02",
    },
  },
  ghostLarge: {
    width: theme.BUTTON_GHOST_LARGE_WIDTH,
    height: theme.BUTTON_GHOST_LARGE_HEIGHT,
    spacing: spaces.padding.stretch.middle,
    color: "transparent",
    colorDisabled: "transparent",
    borderRadius: borderRadius.small,
    text: {
      type: "paragraphXL",
      textColor: "PRYMARY_BASE_02",
      textColorDisabled: "PRYMARY_BASE_02",
      underline: "underline",
    },
  },
  ghostMedium: {
    width: theme.BUTTON_GHOST_MEDIUM_WIDTH,
    height: theme.BUTTON_GHOST_MEDIUM_HEIGHT,
    spacing: spaces.padding.stretch.small,
    color: "transparent",
    colorDisabled: "transparent",
    borderRadius: borderRadius.small,
    text: {
      type: "paragraphXL",
      textColor: "PRYMARY_BASE_02",
      textColorDisabled: "PRYMARY_BASE_02",
      underline: "underline",
    },
  },
  ghostSmall: {
    width: theme.BUTTON_GHOST_SMALL_WIDTH,
    height: theme.BUTTON_GHOST_SMALL_HEIGHT,
    spacing: spaces.padding.stretch.small,
    color: "transparent",
    colorDisabled: "transparent",
    borderRadius: borderRadius.small,
    text: {
      type: "paragraphXL",
      textColor: "PRYMARY_BASE_02",
      textColorDisabled: "PRYMARY_BASE_02",
      underline: "underline",
    },
  },
  quarckIcon: {
    width: theme.BUTTON_QUARCK_ICON_WIDTH,
    height: theme.BUTTON_QUARCK_ICON_HEIGHT,
    spacing: spaces.padding.inner.middle,
    color: "ALERT_COLOR_04",
    borderRadius: borderRadius.medium,
    text: {
      type: "paragraphXXXS",
      textColor: "DARK_BASE_05",
    },
    icon: {
      size: "sx",
      color: "DARK_BASE_05",
    },
  },
  blocked: {
    width: theme.BUTTON_BLOCKED_SMALL_WIDTH,
    height: theme.BUTTON_BLOCKED_SMALL_HEIGHT,
    spacing: spaces.padding.stretch.small,
    color: "PRYMARY_BASE_02",
    colorDisabled: "LIGHT_BASE_03",
    borderRadius: borderRadius.small,
    text: {
      type: "paragraphXL",
      textColor: "LIGHT_BASE_01",
      textColorDisabled: "DARK_BASE_02",
    },
  },
  tiny: {
    width: theme.BUTTON_TINY_WIDTH,
    height: theme.BUTTON_TINY_HEIGHT,
    spacing: spaces.padding.inner.middle,
    color: "SECONDARY_BASE_06",
    colorDisabled: "LIGHT_BASE_03",
    borderRadius: borderRadius.pill,
    text: {
      type: "paragraphMDM",
      textColor: "LIGHT_BASE_01",
      textColorDisabled: "DARK_BASE_02",
    },
  },
};

const styleTextInput = {
  default: {
    width: theme.TEXTINPUT_DEFAULT_WIDTH,
    height: theme.TEXTINPUT_DEFAULT_HEIGHT,
    backgroundColor: "transparent",
    text: {
      type: "paragraphSM",
      textColor: colors.DARK_BASE_02,
      errorTextColor: colors.ERROR_BASE_04,
    },
    label: {
      type: "paragraphLG",
      textColor: colors.DARK_BASE_02,
      errorTextColor: colors.PRYMARY_BASE_02,
      padding: spaces.padding.inner.small,
    },
    description: {
      type: "paragraphSM",
      textColor: colors.PRYMARY_BASE_02,
      errorTextColor: colors.ERROR_BASE_04,
      spacing: "quark",
    },
    shape: {
      backgroundColor: colors.LIGHT_BASE_03,
      borderRadius: theme.BORDER_RADIUS_NONE,
      borderWidth: theme.BORDER_WIDTH_NONE,
      padding: spaces.padding.inner.small,
    },
    border: {
      borderWidth: borderWidth.small,
      borderColor: colors.DARK_BASE_02,
      borderColorDefault: colors.DARK_BASE_02,
      borderColorDisable: colors.DARK_BASE_02,
      borderColorFocused: colors.SECONDARY_BASE_02,
      borderColorActivated: colors.DARK_BASE_05,
      errorBorderColor: colors.ERROR_BASE_04,
    },
    supportText: {
      type: "paragraphSM",
      textColor: colors.ERROR_BASE_04,
      spacing: "quark",
    },
    icon: {
      name: "ic_sp_xs",
      errorColor: colors.ERROR_BASE_04,
      passwordColor: colors.PRYMARY_BASE_01,
    },
  },
  small: {
    width: theme.TEXTINPUT_SMALL_WIDTH,
    height: theme.TEXTINPUT_SMALL_HEIGHT,
    backgroundColor: "transparent",
    text: {
      type: "paragraphSM",
      textColor: colors.PRYMARY_BASE_02,
      textColorDisable: colors.DARK_BASE_02,
      errorTextColor: colors.ERROR_BASE_04,
      placeholderColor: colors.PRYMARY_BASE_02,
    },
    label: {
      type: "paragraphLG",
      textColor: colors.DARK_BASE_02,
      errorTextColor: colors.PRYMARY_BASE_02,
      padding: spaces.padding.inner.small,
    },
    description: {
      type: "paragraphSM",
      textColor: colors.PRYMARY_BASE_02,
      errorTextColor: colors.ERROR_BASE_04,
      spacing: spaces.margins.flat.quark,
    },
    shape: {
      backgroundColor: colors.LIGHT_BASE_03,
      borderRadius: theme.BORDER_RADIUS_NONE,
      borderWidth: theme.BORDER_WIDTH_NONE,
      padding: spaces.padding.inner.small,
    },
    border: {
      borderWidth: borderWidth.small,
      borderColor: colors.DARK_BASE_02,
      borderColorDefault: colors.DARK_BASE_02,
      borderColorDisable: colors.DARK_BASE_02,
      borderColorFocused: colors.SECONDARY_BASE_02,
      borderColorActivated: colors.DARK_BASE_05,
      errorBorderColor: colors.ERROR_BASE_04,
    },
    supportText: {
      type: "paragraphSM",
      textColor: colors.ERROR_BASE_04,
      spacing: spaces.margins.flat.quark,
    },
    icon: {
      name: "ic_sp_xs",
      errorColor: colors.ERROR_BASE_04,
    },
  },
  search: {
    width: theme.TEXTINPUT_SEARCH_WIDTH,
    height: theme.TEXTINPUT_SEARCH_HEIGHT,
    backgroundColor: "LIGHT_BASE_01",
    borderRadius: borderRadius.small,
    text: {
      type: "paragraphSM",
      textColor: colors.DARK_BASE_02,
      errorTextColor: colors.ERROR_BASE_04,
    },
    label: {
      type: "paragraphLG",
      textColor: colors.DARK_BASE_02,
      errorTextColor: colors.PRYMARY_BASE_02,
      padding: spaces.padding.inner.small,
    },
    description: {
      type: "paragraphSM",
      textColor: colors.PRYMARY_BASE_02,
      errorTextColor: colors.ERROR_BASE_04,
      spacing: "quark",
    },
    shape: {
      backgroundColor: colors.LIGHT_BASE_03,
      borderRadius: theme.BORDER_RADIUS_NONE,
      borderWidth: theme.BORDER_WIDTH_NONE,
      padding: spaces.padding.inner.small,
    },
    border: {
      borderWidth: borderWidth.none,
      borderColor: colors.DARK_BASE_02,
      borderColorDefault: colors.DARK_BASE_02,
      borderColorDisable: colors.DARK_BASE_02,
      borderColorFocused: colors.SECONDARY_BASE_02,
      borderColorActivated: colors.DARK_BASE_05,
      errorBorderColor: colors.ERROR_BASE_04,
    },
    supportText: {
      type: "paragraphSM",
      textColor: colors.ERROR_BASE_04,
      spacing: "quark",
    },
    icon: {
      name: "ic_sp_xs",
      errorColor: colors.ERROR_BASE_04,
      passwordColor: colors.PRYMARY_BASE_01,
    },
  },
  searchLigth: {
    width: theme.TEXTINPUT_DEFAULT_WIDTH,
    height: theme.TEXTINPUT_DEFAULT_HEIGHT,
    backgroundColor: "transparent",
    text: {
      type: "paragraphSM",
      textColor: colors.DARK_BASE_02,
      errorTextColor: colors.ERROR_BASE_04,
    },
    label: {
      type: "paragraphLG",
      textColor: colors.DARK_BASE_02,
      errorTextColor: colors.PRYMARY_BASE_02,
      padding: spaces.padding.inner.small,
    },
    description: {
      type: "paragraphSM",
      textColor: colors.PRYMARY_BASE_02,
      errorTextColor: colors.ERROR_BASE_04,
      spacing: "quark",
    },
    shape: {
      backgroundColor: colors.LIGHT_BASE_03,
      borderRadius: theme.BORDER_RADIUS_NONE,
      borderWidth: theme.BORDER_WIDTH_NONE,
      padding: spaces.padding.inner.small,
    },
    border: {
      borderWidth: borderWidth.small,
      borderColor: colors.DARK_BASE_02,
      borderColorDefault: colors.DARK_BASE_02,
      borderColorDisable: colors.DARK_BASE_02,
      borderColorFocused: colors.SECONDARY_BASE_02,
      borderColorActivated: colors.DARK_BASE_05,
      errorBorderColor: colors.ERROR_BASE_04,
    },
    supportText: {
      type: "paragraphSM",
      textColor: colors.ERROR_BASE_04,
      spacing: "quark",
    },
    icon: {
      name: "ic_sp_xs",
      errorColor: colors.ERROR_BASE_04,
      passwordColor: colors.PRYMARY_BASE_01,
    },
  },
};

const styleBackground = {
  default: {
    bgColor: colors.LIGHT_BASE_01,
  },
  secundary: {
    bgColor: colors.LIGHT_BASE_02,
  },
  scrim: {
    bgColor: colors.SECONDARY_BASE_01,
    opacity: opacityLevel.small,
  },
  top: {
    bgColor: [
      `${colors.PRYMARY_BASE_01}`,
      `${colors.PRYMARY_BASE_01}`,
      `${colors.PRYMARY_BASE_01}`,
      `${colors.PRYMARY_BASE_01}${theme.OPACITY_BACKGROUND_TOP[0]}`,
      `${colors.PRYMARY_BASE_01}${theme.OPACITY_BACKGROUND_TOP[1]}`,
    ],
  },
};

const styleIcon = {
  xl: theme.ICON_XL,
  lg: theme.ICON_LG,
  gt: theme.ICON_GT,
  md: theme.ICON_MD,
  sm: theme.ICON_SM,
  xs: theme.ICON_XS,
  sx: theme.ICON_SX,
  xxs: theme.ICON_XXS,
  xxxs: theme.ICON_XXXS,
};

export default {
  fontSize,
  fontWeight,
  borderRadius,
  borderWidth,
  opacityLevel,
  lineHeight,
  styleButton,
  styleText,
  styleTextInput,
  styleBackground,
  spaces,
  shadow,
  styleIcon,
  colors,
};
